#!/bin/sh
#****************************************************************************
# Bot execution script. Simply calls my.dertraktor.imageresizer.bot.Bot class
#****************************************************************************


CLASSPATH="../lib/image-resizer-1.0-DEV-SNAPSHOT.jar\
:../lib/amqp-client-3.6.3.jar\
:../lib/apache-mime4j-0.6.jar\
:../lib/commons-codec-1.3.jar\
:../lib/commons-logging-1.1.1.jar\
:../lib/dropbox-client-1.5.3.jar\
:../lib/dropbox-core-sdk-1.7.7.jar\
:../lib/guava-18.0.jar\
:../lib/http-client-1.0.0.RELEASE.jar\
:../lib/httpclient-4.0.3.jar\
:../lib/httpcore-4.0.1.jar\
:../lib/httpmime-4.0.3.jar\
:../lib/imgscalr-lib-4.2.jar\
:../lib/jackson-annotations-2.5.0.jar\
:../lib/jackson-core-2.4.0-rc3.jar\
:../lib/jackson-databind-2.5.1.jar\
:../lib/json-simple-1.1.jar\
:../lib/log4j-api-2.6.2.jar\
:../lib/log4j-core-2.6.2.jar\
:../lib/spring-amqp-1.6.1.RELEASE.jar\
:../lib/spring-aop-4.3.2.RELEASE.jar\
:../lib/spring-beans-4.3.2.RELEASE.jar\
:../lib/spring-context-4.3.2.RELEASE.jar\
:../lib/spring-core-4.3.2.RELEASE.jar\
:../lib/spring-expression-4.3.2.RELEASE.jar\
:../lib/spring-messaging-4.2.7.RELEASE.jar\
:../lib/spring-rabbit-1.6.1.RELEASE.jar\
:../lib/spring-retry-1.1.3.RELEASE.jar\
:../lib/spring-test-4.3.2.RELEASE.jar\
:../lib/spring-tx-4.2.7.RELEASE.jar\
:../lib/spring-web-4.2.7.RELEASE.jar"

java -cp $CLASSPATH my.dertraktor.imageresizer.bot.Bot  $*
